# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from addPage import *


class Ui_firstPage(object):
    def setupUi(self, firstPage):
        firstPage.setObjectName("firstPage")
        firstPage.resize(712, 552)
        firstPage.setStyleSheet("background-color: rgb(115, 64, 70);")
        self.pushButton = QtWidgets.QPushButton(firstPage)
        self.pushButton.setGeometry(QtCore.QRect(260, 220, 191, 111))
        self.pushButton.setStyleSheet("background-color: rgb(231, 158, 79);\n"
"font: 20pt \"Poor Richard\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(firstPage)
        self.label.setGeometry(QtCore.QRect(90, 390, 151, 101))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(firstPage)
        self.label_2.setGeometry(QtCore.QRect(320, 390, 161, 111))
        self.label_2.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(firstPage)
        QtCore.QMetaObject.connectSlotsByName(firstPage)

        self.pushButton.clicked.connect(self.enteryButton)

    def retranslateUi(self, firstPage):
        _translate = QtCore.QCoreApplication.translate
        firstPage.setWindowTitle(_translate("firstPage", "Form"))
        self.pushButton.setText(_translate("firstPage", "Enter"))
        self.label.setText(_translate("firstPage", "Created by: \n"
"x \n"
"y \n"
"z"))
        self.label_2.setText(_translate("firstPage", "Professor: \n"
"Dr. Seyfadini"))

    def enteryButton(self):
        firstPage.close()
        self.openAddPage()

    def openAddPage(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_addPage()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firstPage = QtWidgets.QWidget()
    ui = Ui_firstPage()
    ui.setupUi(firstPage)
    firstPage.show()
    sys.exit(app.exec_())
