# -*- coding: utf-8 -*-

# mainSearch implementation generated from reading ui file 'MainSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainSearch(object):
    def setupUi(self, mainSearch, y, mo, d, h, mn):
        self.year = y
        self.month = mo
        self.day = d
        self.hour = h
        self.minute = mn
        mainSearch.setObjectName("mainSearch")
        mainSearch.resize(750, 600)
        mainSearch.setStyleSheet("background-color: rgb(238, 214, 196);")
        self.picturePlace = QtWidgets.QLabel(mainSearch)
        self.picturePlace.setGeometry(QtCore.QRect(140, 20, 471, 421))
        self.picturePlace.setText("")
        self.picturePlace.setObjectName("picturePlace")
        self.timeLabel = QtWidgets.QLabel(mainSearch)
        self.timeLabel.setGeometry(QtCore.QRect(150, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setText("")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.checkLabel = QtWidgets.QLabel(mainSearch)
        self.checkLabel.setGeometry(QtCore.QRect(400, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkLabel.setFont(font)
        self.checkLabel.setText("")
        self.checkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.checkLabel.setObjectName("checkLabel")

        self.retranslateUi(mainSearch)
        QtCore.QMetaObject.connectSlotsByName(mainSearch)

    def retranslateUi(self, mainSearch):
        _translate = QtCore.QCoreApplication.translate
        mainSearch.setWindowTitle(_translate("mainSearch", "Searched Picture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainSearch = QtWidgets.QWidget()
    ui = Ui_mainSearch()
    ui.setupUi(mainSearch, 'None', 'None', 'None', 'None', 'None', 'None', 'None')
    mainSearch.show()
    sys.exit(app.exec_())
