# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delMain(object):
    def setupUi(self, delMain, y, mo, d, h, mn):
        self.year = y
        self.month = mo
        self.day = d
        self.hour = h
        self.minute = mn
        delMain.setObjectName("delMain")
        delMain.resize(750, 600)
        delMain.setStyleSheet("background-color: rgb(238, 214, 196);")
        self.picturePlace = QtWidgets.QLabel(delMain)
        self.picturePlace.setGeometry(QtCore.QRect(140, 20, 471, 421))
        self.picturePlace.setText("")
        self.picturePlace.setObjectName("picturePlace")
        self.timeLabel = QtWidgets.QLabel(delMain)
        self.timeLabel.setGeometry(QtCore.QRect(150, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setText("")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.checkLabel = QtWidgets.QLabel(delMain)
        self.checkLabel.setGeometry(QtCore.QRect(400, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkLabel.setFont(font)
        self.checkLabel.setText("")
        self.checkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.checkLabel.setObjectName("checkLabel")
        self.delButton = QtWidgets.QPushButton(delMain)
        self.delButton.setGeometry(QtCore.QRect(330, 520, 111, 51))
        self.delButton.setStyleSheet("background-color: rgb(72, 52, 52);\n"
"color: rgb(255, 243, 228);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/103476_cancel_image_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delButton.setIcon(icon)
        self.delButton.setIconSize(QtCore.QSize(30, 30))
        self.delButton.setObjectName("delButton")

        self.retranslateUi(delMain)
        QtCore.QMetaObject.connectSlotsByName(delMain)


    def retranslateUi(self, delMain):
        _translate = QtCore.QCoreApplication.translate
        delMain.setWindowTitle(_translate("delMain", "Form"))
        self.delButton.setText(_translate("delMain", "Delete"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delMain = QtWidgets.QWidget()
    ui = Ui_delMain()
    ui.setupUi(delMain, 'None', 'None', 'None', 'None', 'None', 'None', 'None')
    delMain.show()
    sys.exit(app.exec_())
