# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 600)
        Form.setStyleSheet("background-color: rgb(238, 214, 196);")
        self.picturePlace = QtWidgets.QLabel(Form)
        self.picturePlace.setGeometry(QtCore.QRect(140, 20, 471, 421))
        self.picturePlace.setText("")
        self.picturePlace.setObjectName("picturePlace")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setGeometry(QtCore.QRect(150, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setText("")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.checkLabel = QtWidgets.QLabel(Form)
        self.checkLabel.setGeometry(QtCore.QRect(400, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkLabel.setFont(font)
        self.checkLabel.setText("")
        self.checkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.checkLabel.setObjectName("checkLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Searched Picture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
